

-- CREATE SEQUENCES
CREATE SEQUENCE IF NOT EXISTS SEQ_SYSTEM_PRICE_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_BRAND_ID;  

-- INSERTS BRANDS
INSERT INTO BRANDS (BRAND_ID , NAME )
VALUES (nextval('SEQ_BRAND_ID'), 'ZARA');

INSERT INTO BRANDS (BRAND_ID , NAME )
VALUES (nextval('SEQ_BRAND_ID'), 'Bershka');

INSERT INTO BRANDS (BRAND_ID , NAME )
VALUES (nextval('SEQ_BRAND_ID'), 'ZARA HOME');


-- INSERTS PRICES
INSERT INTO PRICES (SYSTEM_PRICE_ID , BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR )
VALUES (nextval('SEQ_SYSTEM_PRICE_ID'), SELECT BRAND_ID FROM BRANDS WHERE NAME ='ZARA',  '2020-06-14 00:00:00', '2020-12-31 23:59:59', 1, '35455', 0, 35.50,  'EUR');
 
 
INSERT INTO PRICES (SYSTEM_PRICE_ID , BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR )
VALUES (nextval('SEQ_SYSTEM_PRICE_ID'), SELECT BRAND_ID FROM BRANDS WHERE NAME ='ZARA',  '2020-06-14 15:00:00', '2020-06-14 18:30:00', 2, '35455', 0, 25.45,  'EUR');
 
 
INSERT INTO PRICES (SYSTEM_PRICE_ID , BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR )
VALUES (nextval('SEQ_SYSTEM_PRICE_ID'), SELECT BRAND_ID FROM BRANDS WHERE NAME ='ZARA',  '2020-06-15 00:00:00', '2020-06-15 11:00:00', 3, '35455', 0, 30.50,  'EUR');
 
 
INSERT INTO PRICES (SYSTEM_PRICE_ID , BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR )
VALUES (nextval('SEQ_SYSTEM_PRICE_ID'), SELECT BRAND_ID FROM BRANDS WHERE NAME ='ZARA' ,  '2020-06-15 16:00:00', '2020-12-31 23:59:59', 4, '35455', 0, 38.95,  'EUR');
 
 
 			
									 